apiVersion: v1
kind: Service
metadata:
  name: hub-graphql
spec:
  ports:
  - port: 4000
  selector:
    app: hub-graphql
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hub-graphql
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: hub-graphql
    spec:
      containers:
      - name: hub-graphql
        image: academicpi.azurecr.io/hub-graphql:v30
        envFrom:
        - secretRef:
            name: hub-graphql-secret-cgm5794fcd
        ports:
        - containerPort: 4000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 250m

