apiVersion: v1
kind: Service
metadata:
  name: hub-graphql-admin
spec:
  ports:
  - port: 4000
  selector:
    app: hub-graphql-admin
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: hub-graphql-admin
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: hub-graphql-admin
    spec:
      containers:
      - name: hub-graphql-admin
        image: academicpi.azurecr.io/hub-graphql:v30
        envFrom:
        - secretRef:
            name: hub-graphql-admin-secret-m5tk7795c7
        ports:
        - containerPort: 4000
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 250m

