apiVersion: v1
kind: Service
metadata:
  name: nbs-portal 
spec:
  ports:
  - port: 8888 
  selector:
    app.kubernetes.io/name : nbs-portal 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nbs-portal
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: nbs-portal
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nbs-portal
    spec:
      containers:
      - name: nbs-portal
        image: academicpi.azurecr.io/hub-app-nbs:v2
        env:
        - name: OCS_HUB_CONFIG
          value: config-dv.ini
        ports:
        - containerPort: 8888
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 250m

