apiVersion: v1
kind: Service
metadata:
  name: google-verif 
  namespace: jhub
spec:
  ports:
  - port: 80 
  selector:
    app: google-verif 
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: google-verif 
  namespace: jhub
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: google-verif 
    spec:
      containers:
      - name: data-portal
        image: academicpi.azurecr.io/hub-dataportal:api-v2
        env:
        - name: MAX_ROWS 
          value: "3000"
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m

