apiVersion: apps/v1
kind: Deployment
metadata:
  name: hubauth
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: hubauth
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app.kubernetes.io/name: hubauth
    spec:
      containers:
      - name: hubauth 
        image: academicpi.azurecr.io/hub-auth:v23
        envFrom:
        - secretRef:
            name: auth-portal-secret-b96m4k5c56
        ports:
        - containerPort: 3000 
        resources:
          requests:
            cpu: 50m
          limits:
            cpu: 100m
---
apiVersion: v1
kind: Service
metadata:
  name: hubauth
spec:
  ports:
  - port: 3000
  selector:
    app.kubernetes.io/name: hubauth

