apiVersion: v1
kind: Service
metadata:
  name: nbviewer 
spec:
  ports:
  - port: 8080 
  selector:
    app: nbviewer 
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: nbviewer 
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: nbviewer
    spec:
      containers:
      - name: nbviewer 
        image: academicpi.azurecr.io/nbviewer:v16
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 250m

